from PySide2 import *
from PySide2.QtCore import *
from PySide2.QtGui import *

import shutil
from multiprocessing import cpu_count
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QGraphicsDropShadowEffect
from PyQt5.QtWidgets import QLabel, QTableWidgetItem, QPushButton


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 480)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(49, 16, 99);\n"
"color:white;\n"
"border:none\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setStyleSheet("background-color: rgb(54, 0, 135);\n"
"border-size:2px;\n"
"border-bottom-color: rgb(198, 206, 255);\n"
"cursor:pointer")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_left_frame = QtWidgets.QFrame(self.header_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.header_left_frame.setFont(font)
        self.header_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left_frame.setObjectName("header_left_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_left_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.header_left_frame)
        font = QtGui.QFont()
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:transparent")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("AASTU_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)

        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.header_left_frame, 0, QtCore.Qt.AlignLeft)
        self.header_center_frame = QtWidgets.QFrame(self.header_frame)
        self.header_center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_center_frame.setObjectName("header_center_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_center_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.header_center_frame)
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/5924081491582545602-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.label_3 = QtWidgets.QLabel(self.header_center_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.header_center_frame, 0, QtCore.Qt.AlignLeft)
        self.header_right_frame = QtWidgets.QFrame(self.header_frame)
        self.header_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_right_frame.setObjectName("header_right_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_right_frame)
        self.horizontalLayout_2.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.restore_button= QtWidgets.QPushButton(self.header_right_frame)
        self.restore_button.setStyleSheet("background-color:transparent")
        self.restore_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/squares.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_button.setIcon(icon2)
        self.restore_button.setObjectName("restore_button")
        self.horizontalLayout_2.addWidget(self.restore_button)
        self.minimize_button = QtWidgets.QPushButton(self.header_right_frame)
        self.minimize_button.setStyleSheet("background-color:transparent")
        self.minimize_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon3)
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout_2.addWidget(self.minimize_button)
        self.close_button = QtWidgets.QPushButton(self.header_right_frame)
        self.close_button.setStyleSheet("background-color:transparent\n"
"")
        self.close_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon4)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.horizontalLayout.addWidget(self.header_right_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header_frame)
        self.main_body_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_frame.sizePolicy().hasHeightForWidth())
        self.main_body_frame.setSizePolicy(sizePolicy)
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.main_body_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.left_menu_frame = QtWidgets.QFrame(self.main_body_frame)
        self.left_menu_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.left_menu_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.left_menu_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.menu_frame = QtWidgets.QFrame(self.left_menu_frame)
        self.menu_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.menu_frame.setFont(font)
        self.menu_frame.setStyleSheet("font-size:15px;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.130682 rgba(99, 137, 216, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(54, 0, 135, 0.7);\n"
"\n"
"border-top-left-radius:20px")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 27)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.cpu_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.cpu_page_btn.setStyleSheet("background-color:transparent\n"
"")
        self.cpu_page_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cpu_page_btn.setIcon(icon5)
        self.cpu_page_btn.setIconSize(QtCore.QSize(36, 32))
        self.cpu_page_btn.setObjectName("cpu_page_btn")
        self.gridLayout.addWidget(self.cpu_page_btn, 0, 0, 1, 1)
        self.system_inf_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.system_inf_page_btn.setStyleSheet("background-color:transparent")
        self.system_inf_page_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/data-complexity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.system_inf_page_btn.setIcon(icon6)
        self.system_inf_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.system_inf_page_btn.setObjectName("system_inf_page_btn")
        self.gridLayout.addWidget(self.system_inf_page_btn, 2, 0, 1, 1)
        self.sensor_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.sensor_page_btn.setStyleSheet("background-color:transparent")
        self.sensor_page_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/cctv-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sensor_page_btn.setIcon(icon7)
        self.sensor_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor_page_btn.setObjectName("sensor_page_btn")
        self.gridLayout.addWidget(self.sensor_page_btn, 5, 0, 1, 1)
        self.activity_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.activity_page_btn.setStyleSheet("background-color:transparent")
        self.activity_page_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/pulse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activity_page_btn.setIcon(icon8)
        self.activity_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.activity_page_btn.setObjectName("activity_page_btn")
        self.gridLayout.addWidget(self.activity_page_btn, 3, 0, 1, 1)
        self.storage_page_button = QtWidgets.QPushButton(self.menu_frame)
        self.storage_page_button.setStyleSheet("background-color:transparent")
        self.storage_page_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.storage_page_button.setIcon(icon9)
        self.storage_page_button.setIconSize(QtCore.QSize(32, 32))
        self.storage_page_button.setObjectName("storage_page_button")
        self.gridLayout.addWidget(self.storage_page_button, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.battery_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.battery_page_btn.setStyleSheet("background-color:transparent")
        self.battery_page_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/battery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.battery_page_btn.setIcon(icon10)
        self.battery_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.battery_page_btn.setObjectName("battery_page_btn")
        self.gridLayout.addWidget(self.battery_page_btn, 1, 0, 1, 1)
        self.network_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.network_page_btn.setStyleSheet("background-color:transparent")
        self.network_page_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/20595072161600702605-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.network_page_btn.setIcon(icon11)
        self.network_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.network_page_btn.setObjectName("network_page_btn")
        self.gridLayout.addWidget(self.network_page_btn, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_6 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_8 = QtWidgets.QLabel(self.menu_frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_9 = QtWidgets.QLabel(self.menu_frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_10 = QtWidgets.QLabel(self.menu_frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.menu_frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 1, 1, 1)
        self.horizontalLayout_9.addWidget(self.menu_frame)
        self.horizontalLayout_8.addWidget(self.left_menu_frame)
        self.main_body_content = QtWidgets.QFrame(self.main_body_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_content.sizePolicy().hasHeightForWidth())
        self.main_body_content.setSizePolicy(sizePolicy)
        self.main_body_content.setStyleSheet("background-color: rgb(29, 0, 59);")
        self.main_body_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_content.setObjectName("main_body_content")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.main_body_content)
        self.horizontalLayout_11.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body_content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.cpu_and_storage = QtWidgets.QWidget()
        self.cpu_and_storage.setObjectName("cpu_and_storage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cpu_and_storage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cpu_info_frame = QtWidgets.QFrame(self.cpu_and_storage)
        self.cpu_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cpu_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_info_frame.setObjectName("cpu_info_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.cpu_info_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.cpu_info_frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.cpu_count = QtWidgets.QLabel(self.cpu_info_frame)
        self.cpu_count.setObjectName("cpu_count")
        self.gridLayout_2.addWidget(self.cpu_count, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.cpu_info_frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.cpu_per = QtWidgets.QLabel(self.cpu_info_frame)
        self.cpu_per.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.cpu_per, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.cpu_info_frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.cpu_main_core = QtWidgets.QLabel(self.cpu_info_frame)
        self.cpu_main_core.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.cpu_main_core, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.cpu_info_frame)
        self.ram_info_frame = QtWidgets.QFrame(self.cpu_and_storage)
        self.ram_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ram_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ram_info_frame.setObjectName("ram_info_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ram_info_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.total_ram = QtWidgets.QLabel(self.ram_info_frame)
        self.total_ram.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.total_ram, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.available_ram = QtWidgets.QLabel(self.ram_info_frame)
        self.available_ram.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.available_ram, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 2, 0, 1, 1)
        self.used_ram = QtWidgets.QLabel(self.ram_info_frame)
        self.used_ram.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.used_ram, 2, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 3, 0, 1, 1)
        self.free_ram = QtWidgets.QLabel(self.ram_info_frame)
        self.free_ram.setObjectName("free_ram")
        self.gridLayout_3.addWidget(self.free_ram, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.ram_usage = QtWidgets.QLabel(self.ram_info_frame)
        self.ram_usage.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.ram_usage , 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.ram_info_frame)
        self.stackedWidget.addWidget(self.cpu_and_storage)
        self.battery = QtWidgets.QWidget()
        self.battery.setObjectName("battery")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.battery)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_27 = QtWidgets.QLabel(self.battery)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27, 0, QtCore.Qt.AlignBottom)
        self.frame = QtWidgets.QFrame(self.battery)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(9, 9, 31, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(9, 38, 35, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(9, 67, 44, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(9, 126, 45, 16))
        self.label_31.setObjectName("label_31")
        self.battery_status = QtWidgets.QLabel(self.frame)
        self.battery_status.setGeometry(QtCore.QRect(241, 9, 18, 16))
        self.battery_status.setObjectName("battery_status")
        self.battery_charge = QtWidgets.QLabel(self.frame)
        self.battery_charge.setGeometry(QtCore.QRect(241, 38, 18, 16))
        self.battery_charge.setObjectName("label_33")
        self.battery_time_left = QtWidgets.QLabel(self.frame)
        self.battery_time_left.setGeometry(QtCore.QRect(241, 97, 18, 16))
        self.battery_time_left.setObjectName("label_34")
        self.battery_plugged= QtWidgets.QLabel(self.frame)
        self.battery_plugged.setGeometry(QtCore.QRect(241, 126, 18, 16))
        self.battery_plugged.setObjectName("label_35")
        self.verticalLayout_4.addWidget(self.frame)
        self.stackedWidget.addWidget(self.battery)
        self.system_info = QtWidgets.QWidget()
        self.system_info.setObjectName("system_info")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.system_info)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.system_info)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 4, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 3, 0, 1, 1)
        self.system_date = QtWidgets.QLabel(self.frame_2)
        self.system_date.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.system_date, 1, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_4.addWidget(self.label_48, 4, 2, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.label_47, 3, 2, 1, 1)
        self.system_system = QtWidgets.QLabel(self.frame_2)
        self.system_system.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.system_system, 4, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 2, 0, 1, 1)
        self.system_version = QtWidgets.QLabel(self.frame_2)
        self.system_version.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.system_version, 3, 1, 1, 1)
        self.system_platform = QtWidgets.QLabel(self.frame_2)
        self.system_platform.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.system_platform, 2, 1, 1, 1)
        self.system_processor= QtWidgets.QLabel(self.frame_2)
        self.system_processor.setObjectName("label_50")
        self.gridLayout_4.addWidget(self.system_processor, 2, 3, 1, 1)
        self.system_machine = QtWidgets.QLabel(self.frame_2)
        self.system_machine.setObjectName("label_51")
        self.gridLayout_4.addWidget(self.system_machine, 3, 3, 1, 1)
        self.system_time= QtWidgets.QLabel(self.frame_2)
        self.system_time.setObjectName("label_52")
        self.gridLayout_4.addWidget(self.system_time, 4, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_4.addWidget(self.label_46, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.system_info)
        self.activity = QtWidgets.QWidget()
        self.activity.setObjectName("activity")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.activity)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.activity)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_10.addWidget(self.label_41)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.activity_search = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.activity_search.setFont(font)
        self.activity_search.setStyleSheet("background-color: rgb(65, 65, 180);\n"
"background-color: rgb(176, 188, 255);\n"
"height:30px;\n"
"width:60px;\n"
"border-radius:13px;\n"
"color:white;")
        self.activity_search.setObjectName("lineEdit")
        self.horizontalLayout_12.addWidget(self.activity_search)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/17853935111558096454-128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon12)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_12.addWidget(self.pushButton_5)
        self.horizontalLayout_10.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.activity)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setStyleSheet("font-size:13px;\n"
"color:black;\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.activity)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_13.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_13.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_13.addWidget(self.pushButton_9)
        self.verticalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.activity)
        self.storage = QtWidgets.QWidget()
        self.storage.setObjectName("storage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.storage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_45 = QtWidgets.QLabel(self.storage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_8.addWidget(self.label_45)
        self.storageTable = QtWidgets.QTableWidget(self.storage)
        self.storageTable.setStyleSheet("font-size:13px;\n"
"color:black;")
        self.storageTable.setObjectName("storageTable")
        self.storageTable.setColumnCount(9)
        self.storageTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.storageTable.setHorizontalHeaderItem(8, item)
        self.verticalLayout_8.addWidget(self.storageTable)
        self.stackedWidget.addWidget(self.storage)
        self.sensor = QtWidgets.QWidget()
        self.sensor.setObjectName("sensor")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sensor)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_49 = QtWidgets.QLabel(self.sensor)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_7.addWidget(self.label_49)
        self.sensorTable = QtWidgets.QTableWidget(self.sensor)
        self.sensorTable.setStyleSheet("font-size:13px;\n"
"color:black;")
        self.sensorTable.setObjectName("sensorTable")
        self.sensorTable.setColumnCount(5)
        self.sensorTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sensorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.sensorTable)
        self.stackedWidget.addWidget(self.sensor)
        self.network = QtWidgets.QWidget()
        self.network.setObjectName("network")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.network)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.network)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 605, 484))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_53 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_11.addWidget(self.label_53)
        self.net_stats_table = QtWidgets.QTableWidget(self.frame_8)
        self.net_stats_table.setStyleSheet("font-size:13px;\n"
"background-color: rgb(17, 255, 64);\n"
"color:black;")
        self.net_stats_table.setObjectName("net_stats_table")
        self.net_stats_table.setColumnCount(5)
        self.net_stats_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.net_stats_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_stats_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_stats_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_stats_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_stats_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout_11.addWidget(self.net_stats_table)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_54 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_12.addWidget(self.label_54)
        self.net_io_table = QtWidgets.QTableWidget(self.frame_10)
        self.net_io_table.setStyleSheet("font-size:13px;\n"
"background-color: rgb(252, 255, 41);\n"
"color:black;")
        self.net_io_table.setObjectName("net_io_table")
        self.net_io_table.setColumnCount(9)
        self.net_io_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_io_table.setHorizontalHeaderItem(8, item)
        self.verticalLayout_12.addWidget(self.net_io_table)
        self.verticalLayout_10.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_55 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_13.addWidget(self.label_55)
        self.net_address_table = QtWidgets.QTableWidget(self.frame_11)
        self.net_address_table.setStyleSheet("font-size:13px;\n"
"background-color: rgb(255, 0, 0);\n"
"color:black;")
        self.net_address_table.setObjectName("net_address_table")
        self.net_address_table.setColumnCount(6)
        self.net_address_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_address_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_13.addWidget(self.net_address_table)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_56 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_14.addWidget(self.label_56)
        self.net_connections_table = QtWidgets.QTableWidget(self.frame_12)
        self.net_connections_table.setStyleSheet("font-size:13px;\n"
"background-color: rgb(0, 0, 255);\n"
"color:black;")
        self.net_connections_table.setObjectName("net_connections_table")
        self.net_connections_table.setColumnCount(7)
        self.net_connections_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.net_connections_table.setHorizontalHeaderItem(6, item)
        self.verticalLayout_14.addWidget(self.net_connections_table)
        self.verticalLayout_10.addWidget(self.frame_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.frame_9 = QtWidgets.QFrame(self.network)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.network)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.horizontalLayout_8.addWidget(self.main_body_content)
        self.verticalLayout.addWidget(self.main_body_frame)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        self.footer_frame.setStyleSheet("background-color: rgb(29, 0, 59);")
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.footer_left_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_left_frame.setObjectName("footer_left_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.footer_left_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.footer_left_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.footer_left_frame)
        self.footer_right_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_right_frame.setObjectName("footer_right_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer_right_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.footer_right_frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.footer_right_frame)
        self.frame_3 = QtWidgets.QFrame(self.footer_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(12, 12))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer_frame, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "MENU"))
        self.label_3.setText(_translate("MainWindow", "SYSTEM MONITOR"))
        self.label_4.setText(_translate("MainWindow", "CPU"))
        self.label_5.setText(_translate("MainWindow", "Battery"))
        self.label_6.setText(_translate("MainWindow", "System Information"))
        self.label_8.setText(_translate("MainWindow", "Security_Cam and Network"))
        self.label_9.setText(_translate("MainWindow", "Security CAM"))
        self.label_10.setText(_translate("MainWindow", "Network"))
        self.label_7.setText(_translate("MainWindow", "Activity"))
        self.label_11.setText(_translate("MainWindow", "CPU Count"))
        self.cpu_count.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "CPU Per"))
        self.cpu_per.setText(_translate("MainWindow", "N/A"))
        self.label_13.setText(_translate("MainWindow", "CPU Main Core"))
        self.cpu_main_core.setText(_translate("MainWindow", "N/A"))
        self.label_17.setText(_translate("MainWindow", "Total Ram"))
        self.total_ram.setText(_translate("MainWindow", "N/A"))
        self.label_19.setText(_translate("MainWindow", "Available Ram"))
        self.available_ram.setText(_translate("MainWindow", "N/A"))
        self.label_21.setText(_translate("MainWindow", "User Ram"))
        self.used_ram.setText(_translate("MainWindow", "N/A"))
        self.label_23.setText(_translate("MainWindow", "Free Ram"))
        self.free_ram.setText(_translate("MainWindow", "N/A"))
        self.label_25.setText(_translate("MainWindow", "Ram Usage"))
        self.ram_usage.setText(_translate("MainWindow", "N/A"))
        self.label_27.setText(_translate("MainWindow", "Battery Information"))
        self.label_28.setText(_translate("MainWindow", "Status"))
        self.label_29.setText(_translate("MainWindow", "Charge"))
        self.label_30.setText(_translate("MainWindow", "Time Left"))
        self.label_31.setText(_translate("MainWindow", "Pluged In"))
        self.battery_status.setText(_translate("MainWindow", "N/A"))
        self.battery_charge.setText(_translate("MainWindow", "N/A"))
        self.battery_time_left.setText(_translate("MainWindow", "N/A"))
        self.battery_plugged.setText(_translate("MainWindow", "N/A"))
        self.label_36.setText(_translate("MainWindow", "System Information"))
        self.label_40.setText(_translate("MainWindow", "System"))
        self.label_39.setText(_translate("MainWindow", "Version"))
        self.system_date.setText(_translate("MainWindow", "N/A"))
        self.label_48.setText(_translate("MainWindow", "Syatem-time"))
        self.label_47.setText(_translate("MainWindow", "Machine"))
        self.system_system.setText(_translate("MainWindow", "N/A"))
        self.label_38.setText(_translate("MainWindow", "Platform"))
        self.system_version.setText(_translate("MainWindow", "N/A"))
        self.system_platform.setText(_translate("MainWindow", "N/A"))
        self.system_processor.setText(_translate("MainWindow", "N/A"))
        self.system_machine.setText(_translate("MainWindow", "N/A"))
        self.system_time.setText(_translate("MainWindow", "N/A"))
        self.label_46.setText(_translate("MainWindow", "Processor"))
        self.label_41.setText(_translate("MainWindow", "Activitys"))
        self.activity_search.setPlaceholderText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "process Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "process Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Process Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Started"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Suspended"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resume"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Terminate"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Kill"))
        self.pushButton_6.setText(_translate("MainWindow", "Suspend"))
        self.pushButton_7.setText(_translate("MainWindow", "Resume"))
        self.pushButton_8.setText(_translate("MainWindow", "Terminate"))
        self.pushButton_9.setText(_translate("MainWindow", "Kill"))
        self.label_45.setText(_translate("MainWindow", "Disk Partition"))
        item = self.storageTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device"))
        item = self.storageTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mount Point"))
        item = self.storageTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "OPTS"))
        item = self.storageTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "MAX file"))
        item = self.storageTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MAX path"))
        item = self.storageTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Storage"))
        item = self.storageTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Used Storage"))
        item = self.storageTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Free Storage"))
        self.label_49.setText(_translate("MainWindow", "Sensor"))
        item = self.sensorTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.sensorTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sensor"))
        item = self.sensorTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lable"))
        item = self.sensorTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Critical"))
        self.label_53.setText(_translate("MainWindow", "Status"))
        item = self.net_stats_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISU"))
        item = self.net_stats_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duplex"))
        item = self.net_stats_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.net_stats_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MTU"))
        self.label_54.setText(_translate("MainWindow", "Network I/O Counter"))
        item = self.net_io_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IO"))
        item = self.net_io_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Byte Sent"))
        item = self.net_io_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Byte Receive"))
        item = self.net_io_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Packet Sent"))
        item = self.net_io_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Packet Receive"))
        item = self.net_io_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.net_io_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ERR In"))
        item = self.net_io_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ERR Out"))
        item = self.net_io_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Drop Out"))
        self.label_55.setText(_translate("MainWindow", "Network Address"))
        item = self.net_address_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Family"))
        item = self.net_address_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.net_address_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.net_address_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Broadcast"))
        item = self.net_address_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PTP"))
        self.label_56.setText(_translate("MainWindow", "Network Connection"))
        item = self.net_connections_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FD"))
        item = self.net_connections_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Family"))
        item = self.net_connections_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Family"))
        item = self.net_connections_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "LADOR"))
        item = self.net_connections_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "RADDR"))
        item = self.net_connections_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "PID"))
        self.label.setText(_translate("MainWindow", "Special Group"))
        self.label_2.setText(_translate("MainWindow", "2022 GC/ Oprating System Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
